#!/bin/bash

set -o errexit

rm --recursive --force /a/local/build
mkdir --parents        /a/local/build
cd                     /a/local/build

clang -Wall -Wextra /a/source/main.cpp --output main.exe
