#!/bin/bash

[[ $( uname --operating-system ) == "Msys"                          ]] || { echo "error: unsupported os";         exit 1; }
[[ -x $( command -v python )                                        ]] || { echo "error: python not installed";   exit 1; }
[[ $( python -c "import sys; print( sys.version_info[0] )" ) == "3" ]] || { echo "error: python 3 not installed"; exit 1; }
[[ $( python --version ) == $( cat runtime.txt )                    ]] || { echo "warning: python version mismatch"; }

python -m venv local/venv
scripts/activate
python -m pip install --upgrade pip
pip install --requirement requirements-full.txt
