#!/bin/bash

test() {
	echo testing $1
	pushd $1 > /dev/null

	MSYS_NO_PATHCONV=1 subst /d a: | true && subst a: .

	[[ -f "script/clean"   ]] && script/clean
#	[[ -f "script/install" ]] && script/install
	[[ -f "script/build"   ]] && script/build
	[[ -f "script/run"     ]] && script/run

	popd > /dev/null
}

test $@
