#!/bin/bash

set -o errexit

rm --recursive --force /a/local/build
mkdir --parents        /a/local/build
cd                     /a/local/build

clang -Wall -Wextra -Os -nostdlib -ffreestanding -lkernel32 --output main.exe /a/source/main.cpp
